version: '3'
services:
  orderservice:
    build: ./order-service/
    ports:
      - "8081:8080"
    volumes:
      - ./build/libs:/app
    depends_on:
      - mysql
      - redis
      - cdcservice
      - zipkin
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
      SPRING_DATASOURCE_USERNAME: mysqluser
      SPRING_DATASOURCE_PASSWORD: mysqlpw
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
      REDIS_SERVERS: redis:6379
      REDIS_PARTITIONS: 2
      SPRING_PROFILES_ACTIVE: Redis
      SPRING_SLEUTH_ENABLED: "true"
      SPRING_SLEUTH_SAMPLER_PROBABILITY: 1
      SPRING_ZIPKIN_BASE_URL: http://zipkin:9411/

  customerservice:
    build: ./customer-service/
    ports:
      - "8082:8080"
    volumes:
      - ./build/libs:/app
    depends_on:
      - mysql
      - redis
      - cdcservice
      - zipkin
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
      SPRING_DATASOURCE_USERNAME: mysqluser
      SPRING_DATASOURCE_PASSWORD: mysqlpw
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
      REDIS_SERVERS: redis:6379
      REDIS_PARTITIONS: 2
      SPRING_PROFILES_ACTIVE: Redis
      SPRING_SLEUTH_ENABLED: "true"
      SPRING_SLEUTH_SAMPLER_PROBABILITY: 1
      SPRING_ZIPKIN_BASE_URL: http://zipkin:9411/

  orderhistoryservice:
    build: ./order-history-view-service/
    ports:
      - "8083:8080"
    depends_on:
      - mysql
      - redis
      - zipkin
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
      SPRING_DATASOURCE_USERNAME: mysqluser
      SPRING_DATASOURCE_PASSWORD: mysqlpw
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
      REDIS_SERVERS: redis:6379
      REDIS_PARTITIONS: 2
      SPRING_PROFILES_ACTIVE: Redis
      SPRING_SLEUTH_ENABLED: "true"
      SPRING_SLEUTH_SAMPLER_PROBABILITY: 1
      SPRING_ZIPKIN_BASE_URL: http://zipkin:9411/

## Infrastructure

  zipkin:
    image: openzipkin/zipkin:2.5.0
    ports:
      - "9411:9411"
    environment:
      JAVA_OPTS: -Xmx128m


  zookeeper:
    image: eventuateio/eventuateio-local-zookeeper:0.30.0.M14
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888

  mysql:
    image: eventuateio/eventuate-tram-sagas-mysql:0.10.0.RC2
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw

  redis:
    image: redis:5.0.3
    ports:
      - 6379:6379

  cdcservice:
    image: test-eventuate-tram-cdc-mysql-service
    ports:
      - "8099:8080"
    depends_on:
      - mysql
      - redis
      - zookeeper
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
      SPRING_DATASOURCE_USERNAME: mysqluser
      SPRING_DATASOURCE_PASSWORD: mysqlpw
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      EVENTUATELOCAL_CDC_DB_USER_NAME: root
      EVENTUATELOCAL_CDC_DB_PASSWORD: rootpassword
      EVENTUATELOCAL_CDC_MYSQL_BINLOG_CLIENT_UNIQUE_ID: 1234567890
      EVENTUATELOCAL_CDC_READER_NAME: MySqlReader
      EVENTUATELOCAL_CDC_OFFSET_STORE_KEY: MySqlBinlog
      EVENTUATELOCAL_CDC_READ_OLD_DEBEZIUM_DB_OFFSET_STORAGE_TOPIC: "false"
      SPRING_PROFILES_ACTIVE: Redis
      REDIS_SERVERS: redis:6379
      REDIS_PARTITIONS: 2