version: '3'
services:
  orderservice:
    build: ./order-service/
    ports:
      - "8081:8080"
    volumes:
      - ./build/libs:/app
    depends_on:
      - mysql
      - kafka
      - redis
      - zookeeper
      - cdcservice
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
      SPRING_DATASOURCE_USERNAME: mysqluser
      SPRING_DATASOURCE_PASSWORD: mysqlpw
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      REDIS_HOST: ${DOCKER_HOST_IP}
      REDIS_PORT: 6379
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}

  customerservice:
    build: ./customer-service/
    ports:
      - "8082:8080"
    volumes:
      - ./build/libs:/app
    depends_on:
      - mysql
      - kafka
      - redis
      - zookeeper
      - cdcservice
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
      SPRING_DATASOURCE_USERNAME: mysqluser
      SPRING_DATASOURCE_PASSWORD: mysqlpw
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      REDIS_HOST: ${DOCKER_HOST_IP}
      REDIS_PORT: 6379
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}

  orderhistoryservice:
    build: ./order-history-view-service/
    ports:
      - "8083:8080"
    depends_on:
      - mysql
      - kafka
      - redis
      - zookeeper
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
      SPRING_DATASOURCE_USERNAME: mysqluser
      SPRING_DATASOURCE_PASSWORD: mysqlpw
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      REDIS_HOST: ${DOCKER_HOST_IP}
      REDIS_PORT: 6379
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}

  zookeeper:
    image: eventuateio/eventuateio-local-zookeeper:0.30.0.M14
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888


  kafka:
    image: eventuateio/eventuateio-local-kafka:0.30.0.M14
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      - ADVERTISED_HOST_NAME=${DOCKER_HOST_IP}
      - KAFKA_HEAP_OPTS=-Xmx320m -Xms320m
      - ZOOKEEPER_SERVERS=zookeeper:2181


  mysql:
    image: test-eventuate-tram-mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw

  redis:
    image: redis
    ports:
      - 6379:6379

  cdcservice:
    image: test-eventuate-tram-cdc-mysql-service
    ports:
      - "8099:8080"
    depends_on:
      - mysql
      - kafka
      - redis
      - zookeeper
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
      SPRING_DATASOURCE_USERNAME: mysqluser
      SPRING_DATASOURCE_PASSWORD: mysqlpw
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      EVENTUATELOCAL_CDC_DB_USER_NAME: root
      EVENTUATELOCAL_CDC_DB_PASSWORD: rootpassword
      EVENTUATELOCAL_CDC_BINLOG_CLIENT_ID: 1234567890
      EVENTUATELOCAL_CDC_MYSQL_BINLOG_CLIENT_NAME: MySqlBinlog
      EVENTUATELOCAL_CDC_READ_OLD_DEBEZIUM_DB_OFFSET_STORAGE_TOPIC: "false"
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      REDIS_HOST: ${DOCKER_HOST_IP}
      REDIS_PORT: 6379