version: 2
jobs:
  build:
    machine: true
    working_directory: ~/eventuate-tram-examples-customers-and-orders
    steps:
      - checkout
      - run:
          command: .circleci/install-jdk-14.sh
      - restore_cache:
          keys:
            - eventuate-tram-examples-java-spring-todo-list-{{ checksum "gradle.properties" }}-{{ checksum "pom.xml" }}
            - eventuate-tram-examples-java-spring-todo-list-
      - run:
          command: |
            . ./.circleci/setenv-circle-ci.sh
            ./gradlew testClasses
            ./mvnw package -DskipTests
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.m2
          key: eventuate-tram-examples-java-spring-todo-list-{{ checksum "gradle.properties" }}-{{ checksum "pom.xml" }}
      - run:
          command: |
            . ./.circleci/setenv-circle-ci.sh
            ./build-and-test-all-mysql-binlog.sh
      - run:
          command: |
            . ./.circleci/setenv-circle-ci.sh
            ./build-and-test-all-postgres-polling.sh
      - run:
          command: |
            . ./.circleci/setenv-circle-ci.sh
            ./build-and-test-all-postgres-wal.sh
      - run:
          command: |
            . ./.circleci/setenv-circle-ci.sh
            ./build-and-test-all-mysql-maven.sh
      - run:
          command: |
            ./publish-docker-images.sh
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit ~/container-logs
            docker ps -a > ~/container-logs/containers.txt
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
            sudo bash -c 'find /var/lib/docker/containers -name "*-json.log" -exec cp {} ~/container-logs \;'
            sudo bash -c 'find  ~/container-logs -type f -exec chown circleci {} \;'
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
      - store_artifacts:
          path: ~/container-logs
